### PR TITLE
I18n translation for 'Unsubscribe'

### PR DESCRIPTION
**Pull request by scratchoo**
Needs the ability to translate 'Unsubscribe' word

### CODE REVIEW

**Comment by excid3** [comment]
Thanks! I think we also need to have the "Unsubscribe" string added to the locales files with this change.

**Review by excid3 — CHANGES_REQUESTED** [review]
Let's also update config/locales to include the translation for `Unsubscribe`.

**Comment by scratchoo** [comment]
@excid3 for the Spanish version I added 'Desuscribirse' not sure if this is the correct word, subscribe is translated to Suscribirse there so all I added is "De" 

google translation says it's correct: 

https://translate.google.com/#view=home&op=translate&sl=es&tl=en&text=desuscribirse

I've added some other hardcoded sentences (Note: Spanish translation is from google translate, but I think it's okey until someone else find it to be wrong)

**Comment by scratchoo** [comment]
I added a fr.yml translation file as well...

Note that for : "answered" and "unanswered" I added a translation that is synonym of "solved" and "unsolved" because if for example we click "unanswered" it will show even threads that have answers but no answer is marked as solved, in french the "unanswered" translation is "Sans réponse" which means "without answer", we found that it's misleading in this context, maybe the same apply for the English translation ?

**Comment by excid3** [comment]
Thanks for the work on this! Looking good so far. I just merged the other two PRs which accidentally caused a conflict in the en locale on this PR.

**Comment by scratchoo** [comment]
Hi @excid3 I fixed the conflict, hope this will work as expected. Thanks

**Comment by excid3** [comment]
This looks great to me. 👍

**Pull request merged**
